#!/bin/bash

script_name=$0

# Size ranges and their corresponding Warning and Critical thresholds level
# <1000> plays the role of a limit for <500> and it doesn't have corresponding thresholds
Size_Range=(5 10 20 40 80 250 500 1000)
Warn_Level=(80 80 80 80 90 96 98)
Crit_Level=(90 90 90 90 95 98 99)

# nagios states
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

# current size of the partition
function part_size()
{
    partition="$1"
    size="$(df -h |grep $partition | tail -n1 | awk '{print $2}' | tr -d G/M)"
    if [ "$(df -h |grep $partition | tail -n1 | awk '{print $2}' | tr -d [:digit:])" = "G" ]; then
        echo "$size"
    elif [ "$(df -h |grep $partition | tail -n1 | awk '{print $2}' | tr -d [:digit:])" = "M" ]; then
        echo $(($size/1024))
    fi
}

# Assign warning and critical thresholds based on partition size
# <part_size> value is call result of <function part_size()> that represents the current size of the partition
function assign_alert(){
    partition="$1"
    part_size=$(part_size $partition)
    for item in ${!Size_Range[*]}
    do
        if [[ ($part_size -ge ${Size_Range[$item]}) && ($part_size -lt ${Size_Range[item+1]}) ]] ; then
            warning=${Warn_Level[$item]}
            critical=${Crit_Level[$item]}
        fi
    done
}

function usage()
{
    echo "Invalid options, usage: ${script_name} -w 80 -c 90"
}

function used_percentage_partition()
{
    partition="$1"
    percent="$(df | grep $partition | head -n1 | awk '{print $5}' | tr -d %)"
    echo "$percent"
}


while getopts ":w:c:" opt; do
    case $opt in
    w)
        warning=$OPTARG
        ;;
    c)
        critical=$OPTARG
        ;;
    \?)
        usage
        exit $STATE_UNKNOWN
        ;;
    :)
        echo "Option -$OPTARG requires an argument."
        exit $STATE_UNKNOWN
        ;;
    esac
done

rootfs="$(used_percentage_partition ' /$')"
var="$(used_percentage_partition ' /var$')"
srv="$(used_percentage_partition ' /srv$')"
postgresql="$(used_percentage_partition ' /var/lib/postgresql$')"

target="$rootfs"
assign_alert "/$"
if [ ! -z "$srv" ]; then
    target="$srv"
    assign_alert "/srv$"
elif [ ! -z "$var" ]; then
    target="$var"
    assign_alert "/var$"
elif [ ! -z "$postgresql" ]; then
    target="$postgresql"
    assign_alert "/postgresql$"
fi

MSG="Disk usage ${target}% (warning=${warning}, critical=${critical})"

if [ -z "$target" ]; then
    echo "UNKNOWN: $MSG"
    exit $STATE_UNKNOWN
fi

if [ $target -ge $critical ]; then
    echo "CRITICAL: $MSG"
    exit $STATE_CRITICAL
elif [ $target -ge $warning ]; then
    echo "WARNING: $MSG"
    exit $STATE_WARNING
else
    echo "OK: $MSG"
    exit $STATE_OK
fi
